# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: db_owner
      POSTGRES_DB: zapper
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka_container
    ports:
      - '9092:9092'
      - '9093:9093'
    

  zapier-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zapier_container
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgresuser:db_owner@postgres:5432/zapper
      - KAFKA_BROKERS=kafka:9092
      - PORT=3001
    depends_on:
      - postgres
      - kafka



volumes:
  postgres_data:
  kafka_data:
